rpc:
    name: xq-rpc
    version: 1.0
    serverPort: 9090
    serverHost: 127.0.0.1
    mock: false
    serializer: protostuff
    registryConfig:
        registry: zookeeper
        address: localhost:2181